import { AnalyzedNote } from './types'

export const preAnalyzedNotes: AnalyzedNote[] = [
  {
    id: '1',
    title: '精简喂养yyds！👶 二胎还能继续用的好东西！',
    content:
      '精简姐妹们！养娃两年总结出的真心话：喂养台真的不用满满当当！这套消毒泡奶三合一就足够了，真心是用到二胎都舍不得换的好选择。左边是紫外线消毒柜，承包宝宝所有小物件的消毒！一键启动就能完成消毒+烘干。中间是定量泡奶机，精准控量，保持45℃适宜水温，轻轻一按快速泡奶。右边是摇奶器，泡好的奶直接放进去，自动摇匀不结块、少气泡。从折腾十几分钟到现在3分钟搞定，真的太省心了！',
    author: '宝妈小鹿',
    likes: 2847,
    comments: [
      { content: '这个三合一的多少钱啊？求链接', likes: 23 },
      { content: '我家也是用这个，真的好用！', likes: 15 },
      { content: '摇奶器真的有必要吗？', likes: 8 },
      { content: '二胎妈妈表示同款，真的香', likes: 12 },
      { content: '颜值好高！台面好整洁', likes: 5 },
    ],
    collects: 1632,
    shares: 456,
    coverType: 'story',
    brandMentioned: 'BOLOLO',
    analysis: {
      score: 82,
      strategy: 'acquisition',
      keywords: ['三合一喂养台', '消毒泡奶三合一', '精简喂养', '母婴好物推荐'],
      targetAudience: ['新手妈妈', '备孕/孕期囤货人群', '小户型家庭'],
      strengths: [
        '场景痛点切入精准（台面杂乱→精简方案），引发强共鸣',
        '功能可视化强，三个模块逐一展示，降低理解门槛',
        '评论区购买意向明确（3条问价格/链接）',
      ],
      weaknesses: ['缺少价格信息，可能流失比价用户'],
      recommendation:
        '主投搜索词"三合一喂养台""精简喂养"，定向25-35岁一线城市孕期及0-1岁宝妈。先用Nobid跑3天冷启动，再切oCPC控制CPA在35元以内。建议日预算300元先测试。',
      suggestedBudget: 300,
      expectedCPA: 32,
      commentIntentRate: 0.6,
      contentQuality: '场景化强共情的优质种草文，痛点到方案一气呵成',
      matchScore: { newUser: 88, oldUser: 60 },
    },
    analyzedAt: '2026-07-03T10:30:00Z',
  },
  {
    id: '2',
    title: '三件套🆚三合一⁉来看看怎么个事儿🤔',
    content:
      '给娃挑喂养工具真是选到头大！消毒柜、泡奶机、摇奶器……分开买三大件，家里台面直接变成电器展台。索性两种方案都买回来实测，一边是分开买三件套，另一边是小白熊的三合一喂养台。体验一圈下来，最后还是留了小白熊三合一喂养台。全玻璃的水壶没有任何胶水拼接，消毒柜一次塞8个奶瓶完全足够，摇奶功能也很齐全。算下来比三件分开买好像还更划算一些。',
    author: '阿May的育儿日记',
    likes: 5631,
    comments: [
      { content: '小白熊和波咯咯到底哪个好？纠结中', likes: 67 },
      { content: '刚下单了波咯咯，看完又想换小白熊了😭', likes: 34 },
      { content: '链接链接！', likes: 12 },
      { content: '所以到底选哪个？博主给个结论啊', likes: 28 },
      { content: '我家用的波咯咯也不错', likes: 19 },
      { content: '这种对比太需要了！', likes: 15 },
    ],
    collects: 3821,
    shares: 1204,
    coverType: 'comparison',
    brandMentioned: '小白熊',
    analysis: {
      score: 73,
      strategy: 'acquisition',
      keywords: ['喂养台对比', '三合一喂养台测评', '小白熊 vs', '母婴电器选购'],
      targetAudience: ['犹豫比价的新手妈妈', '母婴电器选购人群', '功能对比型用户'],
      strengths: [
        '横评对比类内容天然适合搜索流量，覆盖大量长尾关键词',
        '评论区互动热烈，真实购买意向高（"小白熊和波咯咯哪个好"）',
        '投票式内容刺激评论和收藏，CES加权高',
      ],
      weaknesses: ['提及的是竞品小白熊而非BOLOLO，需调整投流策略为截流', '笔记结论偏向竞品，BOLOLO需准备对比话术反击'],
      recommendation:
        '作为截流广告投放。定向搜索"小白熊喂养台""三合一测评"的用户，落地页引导至BOLOLO对比内容。出价可高于常规20%，因为截流场景转化率高。日预算200元，重点抢竞品流量。',
      suggestedBudget: 200,
      expectedCPA: 28,
      commentIntentRate: 0.7,
      contentQuality: '高质量的横评对比，互动率极高，评论区是天然的截流阵地',
      matchScore: { newUser: 85, oldUser: 40 },
    },
    analyzedAt: '2026-07-03T10:31:00Z',
  },
  {
    id: '3',
    title: '心累…未买普通消毒柜的朋友听劝吧…',
    content:
      '不了解奶瓶消毒柜的，宁可用开水煮也别买普通消毒柜。像我家有娃后入手的普通消毒柜发现了一些在网上根本了解不到的问题。奶瓶里总是湿漉漉的，查了很多资料才知道是烘干风道设计有问题。建议选能探入奶瓶内部烘干的，选紫外灯珠能伸入奶瓶的，选真正0臭氧0紫外泄露的，选操作简单的，选工作声音轻的。内胆和层架一定要全304不锈钢的，别选塑料的！',
    author: '养娃避坑指南',
    likes: 12453,
    comments: [
      { content: '学到了！正准备买消毒柜，还好看到这篇', likes: 156 },
      { content: '求推荐具体型号！', likes: 89 },
      { content: '波咯咯的消毒柜是不是符合这些标准？', likes: 45 },
      { content: '已收藏，太有用了', likes: 23 },
      { content: '那小白熊的怎么样？', likes: 34 },
    ],
    collects: 8972,
    shares: 3201,
    coverType: 'tip',
    brandMentioned: 'BOLOLO',
    analysis: {
      score: 95,
      strategy: 'both',
      keywords: ['奶瓶消毒柜怎么选', '紫外线消毒柜推荐', '消毒柜选购攻略', '母婴消毒柜避坑', '304不锈钢消毒柜'],
      targetAudience: ['首次购买消毒柜的新手爸妈', '被劣质消毒柜坑过想换的用户', '追求安全材质的高端用户'],
      strengths: [
        '避坑攻略类内容信任度极高，读者会主动搜索品牌验证',
        '评论区出现了"波咯咯是否符合"的品牌主动关联，投流转化率预计很高',
        '内容覆盖7个选购维度，长尾关键词极丰富，搜索流量天花板高',
        '收藏量接近9000，说明内容被大量用户保存为购买参考',
      ],
      weaknesses: ['正文未直接推荐品牌，投流时需配合落地页做品牌引导', '评论区需要主动回复引导至BOLOLO产品'],
      recommendation:
        '重点投流笔记，建议日预算500元。投放策略：搜索词覆盖"消毒柜怎么选""消毒柜推荐"等决策词，人群定向25-35岁孕期及0-1岁宝妈。同时在评论区安排KOC回复"波咯咯都符合这些标准，我用了一年很满意"做截流引导。',
      suggestedBudget: 500,
      expectedCPA: 25,
      commentIntentRate: 0.75,
      contentQuality: '教科书级别的避坑攻略，收藏率极高，是天然的长期种草资产',
      matchScore: { newUser: 92, oldUser: 85 },
    },
    analyzedAt: '2026-07-03T10:32:00Z',
  },
  {
    id: '4',
    title: '波咯咯三合一喂养台大跳水！',
    content:
      '年中大促618！波咯咯旗舰店5折！三合一喂养台终于降了，消毒泡奶摇奶一台搞定，全玻璃壶身+不锈钢内胆，13L大容量，10分钟快速消毒。姐妹们冲！',
    author: '好价挖掘机',
    likes: 893,
    comments: [
      { content: '真的假的？链接来一个', likes: 5 },
      { content: '618买的，比平时便宜了300多', likes: 12 },
      { content: '冲冲冲', likes: 2 },
    ],
    collects: 234,
    shares: 89,
    coverType: 'review',
    brandMentioned: 'BOLOLO',
    analysis: {
      score: 68,
      strategy: 'retention',
      keywords: ['波咯咯618', '波咯咯优惠', '母婴电器促销', '喂养台好价'],
      targetAudience: ['已种草等待优惠的老用户', '价格敏感型用户', '大促期间活跃用户'],
      strengths: ['促销信息明确，对等待价格的用户有强驱动力', '品牌名称明确，精准触达品牌意向人群'],
      weaknesses: [
        '纯促销内容对新用户吸引力弱，不适合拉新',
        '内容深度不足，互动数据一般，自然流量天花板低',
      ],
      recommendation:
        '仅在大促期间投放，定向搜索"波咯咯"品牌词的用户和已互动过品牌笔记的人群。日预算150元，ROI预期高因为触达的是已种草人群。非大促期间不建议投流。',
      suggestedBudget: 150,
      expectedCPA: 18,
      commentIntentRate: 0.5,
      contentQuality: '促销信息类内容，时效性强，适合短期收割但无长期价值',
      matchScore: { newUser: 20, oldUser: 90 },
    },
    analyzedAt: '2026-07-03T10:33:00Z',
  },
  {
    id: '5',
    title: '9.28预产期，因为摇奶器和月嫂争执不下……',
    content:
      '预产期9.28，整理待产包直接跟月嫂吵了两句。她上来就催我买摇奶器，我当时第一反应就是她想偷懒！月嫂才跟我掰扯说手动摇奶把控不好力度，满瓶都是气泡，奶粉还搅不匀，新生儿喝了胀气肠绞痛。东西到家试了几天，奶是肉眼可见的丝滑很少结块起泡，夜里屏幕不晃眼，声音也轻。顺带提一嘴，市面上仿款特别多，下单一定要擦亮眼睛。',
    author: '小糯米妈妈',
    likes: 4321,
    comments: [
      { content: '我也是被月嫂安利的摇奶器哈哈哈', likes: 87 },
      { content: '所以到底买的哪个牌子的？', likes: 56 },
      { content: '预产期10月的我来抄作业了', likes: 34 },
      { content: '这个博主好真实，关注了', likes: 22 },
      { content: '照片拍得好好看，是用什么相机拍的呀', likes: 41 },
    ],
    collects: 2104,
    shares: 678,
    coverType: 'story',
    brandMentioned: '小白熊',
    analysis: {
      score: 65,
      strategy: 'acquisition',
      keywords: ['摇奶器有必要吗', '待产包清单', '新生儿喂养', '摇奶器推荐'],
      targetAudience: ['孕晚期准妈妈', '待产包准备中的人群', '纠结是否买摇奶器的人'],
      strengths: ['场景故事真实性强，冲突设置（和月嫂争执）吸引阅读', '针对"摇奶器是不是智商税"这个决策痛点直接回应'],
      weaknesses: [
        '评论区大量夸博主拍照好看，购买意向被稀释',
        '正文未明确推荐品牌，竞品截流难度大',
        '互动虽高但产品转化信号不够强',
      ],
      recommendation:
        '可小预算测试投流。定向搜索"待产包""摇奶器有必要吗"的用户，落地页用BOLOLO摇奶器对比内容承接。但该笔记评论区品牌信号弱，不建议作为主力投流笔记。日预算100元试水即可。',
      suggestedBudget: 100,
      expectedCPA: 42,
      commentIntentRate: 0.35,
      contentQuality: '故事性强但种草力不足，评论区偏离产品讨论转向博主个人',
      matchScore: { newUser: 70, oldUser: 30 },
    },
    analyzedAt: '2026-07-03T10:34:00Z',
  },
  {
    id: '6',
    title: '全网最全选奶瓶消毒柜攻略！',
    content:
      '做了快一周的功课，买了几台比较中意的消毒柜才总结出来的选购攻略！选消毒柜只要看消毒、烘干、过滤系统三个大点。消毒要双重消毒（灯珠+粒子），材质一定要全不锈钢不要带塑料的，小月龄尽量带快速消烘。烘干要双风机双风道才能烘得干，烘干一定要静音。过滤一定要选尼龙+HEPA的！',
    author: '理科妈妈爱较真',
    likes: 8921,
    comments: [
      { content: '理科妈妈的攻略就是靠谱！', likes: 112 },
      { content: '所以最后买了哪款？求抄作业', likes: 78 },
      { content: '波咯咯X60符合这些标准吗？在线等', likes: 34 },
      { content: '我家用的波咯咯，确实都符合', likes: 28 },
      { content: '收藏了，买之前再来看一遍', likes: 15 },
    ],
    collects: 6745,
    shares: 2103,
    coverType: 'tip',
    brandMentioned: 'BOLOLO',
    analysis: {
      score: 90,
      strategy: 'both',
      keywords: ['奶瓶消毒柜选购', '消毒柜攻略', '双风机双风道消毒柜', 'HEPA过滤消毒柜', '全不锈钢消毒柜'],
      targetAudience: ['理性决策型宝爸宝妈', '喜欢做功课的选购人群', '对消毒效果有高要求的用户'],
      strengths: [
        '结构化攻略内容权威感强，收藏率达75%，是长期搜索流量资产',
        '评论区有用户主动提及BOLOLO并得到其他用户验证，品牌信任度加成',
        '覆盖"消毒+烘干+过滤"三大决策维度，几乎匹配BOLOLO所有核心卖点',
      ],
      weaknesses: ['内容较长，需注意信息流广告的完读率'],
      recommendation:
        '核心投流笔记之一，建议日预算400元。搜索广告为主，覆盖"消毒柜选购""消毒柜怎么选""最好用的消毒柜"等决策期搜索词。信息流广告定向"家电攻略""母婴好物"兴趣标签用户。预计转化率高于均值30%。',
      suggestedBudget: 400,
      expectedCPA: 22,
      commentIntentRate: 0.65,
      contentQuality: '高价值攻略内容，天然的品牌信任放大器',
      matchScore: { newUser: 90, oldUser: 78 },
    },
    analyzedAt: '2026-07-03T10:35:00Z',
  },
  {
    id: '7',
    title: '新手妈妈消毒柜不专业对比',
    content:
      '买了两个消毒柜，有姐妹也可以帮忙参考一下。小白熊用下来的感觉：有可视天窗，25L容量分三层，烘干温度可以高温低温任意选，滤网可水洗。波洛洛使用感受：可以手机连接，同样25L容量但外观小巧，升级了15分钟消烘模式，HEPA过滤。总体用下来区别不大，细节上波洛洛有个置物篮比较方便，直接放进去洗完拿去烘干。',
    author: '新手妈妈上路',
    likes: 3245,
    comments: [
      { content: '刚好在纠结这两款，谢谢博主！', likes: 45 },
      { content: '波洛洛的APP控制好用吗？', likes: 23 },
      { content: '15分钟消烘真的快，适合夜奶多的', likes: 18 },
      { content: '小白熊是不是也有APP款？', likes: 12 },
    ],
    collects: 2187,
    shares: 534,
    coverType: 'comparison',
    brandMentioned: 'BOLOLO',
    analysis: {
      score: 78,
      strategy: 'both',
      keywords: ['消毒柜对比', '小白熊vs波洛洛', '奶瓶消毒柜测评', '母婴消毒柜推荐'],
      targetAudience: ['在小白熊和BOLOLO之间纠结的用户', '首次购买消毒柜的新手', '注重便捷性的宝妈'],
      strengths: [
        '直接对比BOLOLO和竞品小白熊，是典型的截流+截胡内容',
        '结论偏BOLOLO（"波洛洛有置物篮更方便"），品牌倾向明确',
        '搜索"小白熊vs波洛洛"的用户购买意图极强，转化率高',
      ],
      weaknesses: ['标题自称"不专业"，可能降低权威感', '互动量相对中等'],
      recommendation:
        '投搜索广告，重点抢"消毒柜对比""小白熊vs""消毒柜推荐"等关键词。出价可以略高，因为搜索这些词的用户基本是最终决策阶段，转化率高。日预算250元，配合品牌专区做转化闭环。',
      suggestedBudget: 250,
      expectedCPA: 26,
      commentIntentRate: 0.55,
      contentQuality: '精准的截流型对比内容，品牌立场明确但不生硬',
      matchScore: { newUser: 75, oldUser: 82 },
    },
    analyzedAt: '2026-07-03T10:36:00Z',
  },
  {
    id: '8',
    title: '波洛洛一体式吸奶器闲置，用过三四次，有需要私',
    content: '波洛洛一体式吸奶器闲置，用过三四次，功能正常，配件齐全。有需要的姐妹私信我。',
    author: '闲置转让小号',
    likes: 12,
    comments: [
      { content: '多少钱出？', likes: 1 },
      { content: '还在吗', likes: 0 },
    ],
    collects: 3,
    shares: 1,
    coverType: 'review',
    brandMentioned: 'BOLOLO',
    analysis: {
      score: 15,
      strategy: 'not_recommended',
      keywords: [],
      targetAudience: [],
      strengths: [],
      weaknesses: ['二手闲置转让内容，暗示产品被弃用，对品牌形象负面', '互动极低，无任何种草价值', '投流会放大负面信号'],
      recommendation: '不建议投流。此类内容出现在搜索结果中可能影响品牌形象。建议联系博主协商下架或转为正向使用体验内容。投流预算应分配给正向种草笔记。',
      suggestedBudget: 0,
      expectedCPA: 0,
      commentIntentRate: 0,
      contentQuality: '负面信号内容，不建议任何付费推广',
      matchScore: { newUser: 0, oldUser: 0 },
    },
    analyzedAt: '2026-07-03T10:37:00Z',
  },
  {
    id: '9',
    title: '不是，这个全玻璃设计要300+❓️❗️😲',
    content:
      '新手宝妈直接一眼心动！终于不用跟塑料内胆、胶水残留较劲了。全壶身高硼硅玻璃+不锈钢可拆洗管道，通透到能看见每一滴水流动，干净度一目了然。45℃恒温稳定+定量出水，37-95℃宽幅可调，1度1调很精准。夜奶党真的爱了，风冷降温+72小时恒温在线。2.5L大容量，一天加一次水就够。自从有了它，泡奶从手忙脚乱变成一键搞定。',
    author: '洁癖妈妈小Q',
    likes: 3567,
    comments: [
      { content: '300多的泡奶机贵吗？我觉得值', likes: 23 },
      { content: '哪个牌子的？求链接', likes: 34 },
      { content: '全玻璃确实安心，塑料的总觉得有味道', likes: 18 },
      { content: '哪里买？', likes: 8 },
    ],
    collects: 1876,
    shares: 432,
    coverType: 'review',
    brandMentioned: 'BOLOLO',
    analysis: {
      score: 79,
      strategy: 'acquisition',
      keywords: ['全玻璃泡奶机', '定量出水泡奶机', '恒温泡奶机', '母婴泡奶神器'],
      targetAudience: ['对材质安全有高要求的宝妈', '夜间频繁泡奶的新手妈妈', '颜值+功能并重的用户'],
      strengths: [
        '全玻璃材质的差异化卖点突出，直击"塑料管道有异味"的品类痛点',
        '功能描述具体（温度范围、容量、风冷降温），专业性带来信任感',
        '评论区多品牌不详的求链接评论，说明种草成功',
      ],
      weaknesses: ['价格敏感型用户会被标题"300+"劝退', '缺少与其他品牌的具体对比'],
      recommendation:
        '搜索广告主投"全玻璃泡奶机""定量泡奶机""恒温调奶器"等关键词。信息流广告定向"母婴好物""宝宝喂养"标签用户。日预算300元。评论区建议KOC回复BOLOLO品牌信息，承接求链接流量。',
      suggestedBudget: 300,
      expectedCPA: 30,
      commentIntentRate: 0.55,
      contentQuality: '产品差异化卖点清晰，信任度高，是优质的拉新种草内容',
      matchScore: { newUser: 84, oldUser: 65 },
    },
    analyzedAt: '2026-07-03T10:38:00Z',
  },
  {
    id: '10',
    title: '买了两次消毒泡奶三合一都退了……',
    content:
      '开始跟风入了一款恒温壶三合一，觉得就倒个水能有多麻烦，结果生完才知道一天泡奶七八次起步，宝宝一哭急得手忙脚乱，越用越崩溃。后来又换了一台能定量出水的泡奶机，结果因为出水过管道，一烧水就一股塑料味，冲出来的水我自己都不敢喝。朋友直接推了波咯咯三合一，一按就出恒温水，出水完全没味道，无管道设计太安心了。消毒柜在三合一里算大容量了，真心劝准备囤货的宝妈别只看颜值。',
    author: '踩坑大王',
    likes: 7654,
    comments: [
      { content: '跟我一模一样！我也退了两个才买到波咯咯', likes: 134 },
      { content: '早看到这篇就好了，我也是退了又退', likes: 67 },
      { content: '波咯咯真的没有塑料味吗？最怕这个', likes: 45 },
      { content: '求链接！！', likes: 23 },
      { content: '所以波咯咯和普通的有管道款差别到底在哪？', likes: 34 },
    ],
    collects: 4892,
    shares: 1567,
    coverType: 'story',
    brandMentioned: 'BOLOLO',
    analysis: {
      score: 91,
      strategy: 'both',
      keywords: ['消毒泡奶三合一', '波咯咯三合一', '泡奶机塑料味', '喂养台推荐', '无管道泡奶机'],
      targetAudience: ['被劣质泡奶机坑过的换购用户', '第一次购买想一步到位的用户', '对水质安全敏感的高端宝妈'],
      strengths: [
        '二次退货的踩坑故事可信度极高，读者代入感强',
        '"无管道"核心卖点通过对比自然引出，不像是广告',
        '评论区大量"我也是"共鸣评论，社交证明效应极强',
        '收藏近5000，是典型的高价值搜索流量长期资产',
      ],
      weaknesses: ['内容较长，信息流展示前3行需抓住注意力'],
      recommendation:
        '最强投流笔记之一，日预算500元。搜索广告覆盖"三合一喂养台推荐""泡奶机塑料味""波咯咯测评"等词。信息流广告用"退了两次才找到它"作为前3行钩子。该笔记ROI预计在所有笔记中排名前3。',
      suggestedBudget: 500,
      expectedCPA: 20,
      commentIntentRate: 0.8,
      contentQuality: '踩坑逆袭类内容信任度天花板，评论区社交证明叠加，种草转化率极高',
      matchScore: { newUser: 86, oldUser: 92 },
    },
    analyzedAt: '2026-07-03T10:39:00Z',
  },
  {
    id: '11',
    title: 'What❓小月龄出行全靠这只移动冲奶杯',
    content:
      '每次带小福宝出门撒欢，最让人头大的就是冲奶水温问题。热水晾半天，凉水冲不开奶粉。自从入手BRUNO便携恒温杯，带娃出行直接幸福感拉满。2分多钟就能热到日常泡奶温度，一键开启巴氏消毒，316L母婴级内胆，保温10小时。暖水+暖奶双模式，母乳、奶粉、水奶全都能适配。带着小福宝逛公园不用到处借热水了。',
    author: '遛娃达人Mia',
    likes: 2187,
    comments: [
      { content: 'BRUNO这个小杯子颜值真的高', likes: 45 },
      { content: '博主拍得好好看！用什么滤镜', likes: 34 },
      { content: '这个和波咯咯的便携款哪个好用？', likes: 12 },
      { content: '好可爱啊啊啊', likes: 28 },
      { content: '博主的宝宝也好可爱', likes: 56 },
    ],
    collects: 1234,
    shares: 345,
    coverType: 'scenario',
    brandMentioned: 'BRUNO',
    analysis: {
      score: 42,
      strategy: 'not_recommended',
      keywords: ['便携恒温杯', '出门冲奶', '母婴出行好物'],
      targetAudience: ['经常带娃外出的宝妈', '颜值党'],
      strengths: ['使用场景清晰，定位精准（外出冲奶痛点）'],
      weaknesses: [
        '评论区大量夸博主好看/宝宝可爱/拍照好，购买意向被严重稀释',
        '推广的是BRUNO而非BOLOLO，品牌错位',
        '"这个好可爱""博主好会拍"类评论占了60%，产品相关讨论极少',
      ],
      recommendation:
        '不建议BOLOLO投流。虽然内容质量不错，但评论信号表明该内容更像"博主个人IP内容"而非"产品种草内容"。如果BOLOLO有便携产品线，可以让KOC另做专门的内容，而非投这篇。',
      suggestedBudget: 0,
      expectedCPA: 0,
      commentIntentRate: 0.1,
      contentQuality: '博主个人IP属性强，产品种草力弱，评论区偏离产品',
      matchScore: { newUser: 25, oldUser: 15 },
    },
    analyzedAt: '2026-07-03T10:40:00Z',
  },
  {
    id: '12',
    title: '波咯咯X60旗舰店！终于大跳水！',
    content: '波咯咯X60旗舰店终于降价了，25L大容量消毒柜，手机APP控制，升级15分钟消烘模式。家用母婴消毒柜天花板，家里有娃的赶紧趁这波入手。',
    author: '剁手指南',
    likes: 567,
    comments: [
      { content: '终于降了！！', likes: 8 },
      { content: '已下单', likes: 5 },
    ],
    collects: 123,
    shares: 45,
    coverType: 'review',
    brandMentioned: 'BOLOLO',
    analysis: {
      score: 55,
      strategy: 'retention',
      keywords: ['波咯咯X60', '波咯咯优惠', '消毒柜降价'],
      targetAudience: ['已种草波咯咯X60的用户', '比价等待中的用户'],
      strengths: ['品牌词精准，直接转化意向用户'],
      weaknesses: ['内容过于简短，无差异化信息', '互动低，只有促销信息没有种草内容'],
      recommendation: '大促期间配合品牌专区投放，不适合作为独立投流笔记。可作为品牌搜索广告的素材之一，日预算100元以内。',
      suggestedBudget: 100,
      expectedCPA: 15,
      commentIntentRate: 0.4,
      contentQuality: '纯促销内容，转化现有意向用户有效但无拉新价值',
      matchScore: { newUser: 10, oldUser: 85 },
    },
    analyzedAt: '2026-07-03T10:41:00Z',
  },
  {
    id: '13',
    title: '谁懂啊！直接承包我所有喂养摆烂日常',
    content:
      '当了妈之后真的深有体会，宝宝的东西越买越多，奶瓶暖奶器消毒器摆得到处都是。做了好多功课对比了好几款，最后入了这款小白熊三合一喂养台。省空间、材质安全可靠，整个烧水壶是一体全玻璃水壶。自带摇奶消毒泡奶三合一功能太香了！13L全不锈钢大容量，最关键它是三合一一体设计，体积小巧不笨重，放床边柜子旁刚刚好。每个区域都是独立工作，不用担心一坏坏所有。',
    author: '摆烂带娃选手',
    likes: 4231,
    comments: [
      { content: '我也是嫌东西太多才买的三合一', likes: 56 },
      { content: '小白熊和波咯咯选哪个啊纠结死了', likes: 78 },
      { content: '波咯咯也有三合一，博主看过吗', likes: 34 },
      { content: '求链接求链接', likes: 12 },
    ],
    collects: 2876,
    shares: 678,
    coverType: 'story',
    brandMentioned: '小白熊',
    analysis: {
      score: 70,
      strategy: 'acquisition',
      keywords: ['三合一喂养台', '省空间喂养台', '小白熊喂养台', '母婴喂养神器'],
      targetAudience: ['家里空间小的小户型家庭', '被杂乱台面困扰的宝妈', '追求一体化解决方案的用户'],
      strengths: [
        '"摆烂带娃"切中目标人群心态，共鸣强',
        '评论区有用户主动提BOLOLO，截流机会明确',
        '内容说服力足够，买家秀式真实体验',
      ],
      weaknesses: ['推荐的是竞品小白熊，需要截流策略', '与BOLOLO品牌无直接关联'],
      recommendation:
        '作为截流广告投放。搜索广告定向"三合一喂养台""小白熊喂养台"等词，出价可高于均值20%。落地页引导至BOLOLO三合一对比内容。评论区安排KOC回复"波咯咯也有三合一，全玻璃+无管道，可以对比看看"。日预算200元。',
      suggestedBudget: 200,
      expectedCPA: 35,
      commentIntentRate: 0.5,
      contentQuality: '高质量竞品种草文，评论区是BOLOLO的截流机会窗口',
      matchScore: { newUser: 72, oldUser: 35 },
    },
    analyzedAt: '2026-07-03T10:42:00Z',
  },
  {
    id: '14',
    title: '小白熊这两款喂养台我都试过了，我有发言权',
    content:
      '这两款喂养台我都是自己用过的。先说说新款二合一+八爪鱼摇奶器这个组合，摇奶功能做得非常专注。那为什么我后来还是换了三合一呢？一是省空间，二合一加八爪鱼相当于两台机器。二是操作太方便了，三合一集温奶摇奶泡奶消毒烘干于一体。三是储物空间真的够大。当然我不是说二合一不好，但如果台面太小，你还是买三合一吧。',
    author: '用过才敢说的老母亲',
    likes: 3876,
    comments: [
      { content: '八爪鱼那个摇奶器真的稳', likes: 34 },
      { content: '博主三合一是哪个牌子的？', likes: 28 },
      { content: '我也在纠结二合一还是三合一', likes: 45 },
    ],
    collects: 2543,
    shares: 567,
    coverType: 'comparison',
    brandMentioned: '小白熊',
    analysis: {
      score: 75,
      strategy: 'both',
      keywords: ['喂养台二合一vs三合一', '小白熊喂养台', '喂养台哪个好', '小白熊八爪鱼'],
      targetAudience: ['在二合一和三合一之间纠结的用户', '空间有限的宝妈', '已有二合一考虑升级的用户'],
      strengths: [
        '博主自称两种都用过，可信度高',
        '精准覆盖"二合一vs三合一"的决策搜索词',
        '评论区购买决策信号明显',
      ],
      weaknesses: ['推荐的是小白熊，BOLOLO需要截流', '笔记结论偏向小白熊三合一'],
      recommendation:
        '截流广告。搜索广告定向"二合一vs三合一""喂养台怎么选"等决策词。BOLOLO可准备对标内容，在落地页展示"BOLOLO三合一的差异化优势（全玻璃无管道 vs 小白熊有管道）"。日预算200元。',
      suggestedBudget: 200,
      expectedCPA: 33,
      commentIntentRate: 0.5,
      contentQuality: '精准覆盖决策阶段用户，但需截流策略配合',
      matchScore: { newUser: 70, oldUser: 65 },
    },
    analyzedAt: '2026-07-03T10:43:00Z',
  },
  {
    id: '15',
    title: '新贝和波咯咯都用过，终于不堵奶了',
    content:
      '两款吸奶器都用过，简单说下真实体验。一开始用的是波咯咯V30，功能挺全，吸力也够，可以APP调模式档位。后来同事推荐了新贝AI小魔镜吸奶器，泌乳模式能模仿宝宝吸吮，微震通乳，边震动边按摩，轻微堵奶在家就能吸开。小结：不怎么堵奶的波咯咯V30挺好用的，经常堵奶的可以试试新贝AI小魔镜。',
    author: '堵奶专业户',
    likes: 4532,
    comments: [
      { content: '我就是堵奶体质，新贝真的救我命', likes: 67 },
      { content: '波咯咯V30和新贝都买了，确实各有优势', likes: 34 },
      { content: '那波咯咯是不是不适合容易堵奶的？', likes: 45 },
      { content: '所以波咯咯被新贝比下去了吗？', likes: 23 },
    ],
    collects: 2876,
    shares: 876,
    coverType: 'comparison',
    brandMentioned: 'BOLOLO',
    analysis: {
      score: 58,
      strategy: 'both',
      keywords: ['吸奶器对比', '波咯咯vs新贝', '堵奶吸奶器', '微震通乳吸奶器'],
      targetAudience: ['经常堵奶的哺乳期妈妈', '选吸奶器的孕期准妈妈', '母婴电器对比党'],
      strengths: ['覆盖"堵奶吸奶器"这个高意图搜索场景', '两个品牌都提了，搜索权重好'],
      weaknesses: [
        '结论对BOLOLO不利（"经常堵奶的建议新贝"），投流可能适得其反',
        '评论区出现"波咯咯被新贝比下去了"的负面解读',
        '投流会放大不利于BOLOLO的信息',
      ],
      recommendation:
        '谨慎投流。如果要投，需要配合评论区运营——安排KOC回复"波咯咯V30主打舒适不疼，不是医用级通乳。大贝贝才是堵奶专用，不同产品线定位不同"来纠正误解。或者不投这篇，让BOLOLO产出一篇"波咯咯吸奶器全系列对比"的正向内容。',
      suggestedBudget: 100,
      expectedCPA: 45,
      commentIntentRate: 0.4,
      contentQuality: '内容客观但结论对BOLOLO不利，投流风险大于收益',
      matchScore: { newUser: 45, oldUser: 55 },
    },
    analyzedAt: '2026-07-03T10:44:00Z',
  },
  {
    id: '16',
    title: '几十元介个母乳神器，我怎么没有早发现',
    content: '求大数据推给还不会免手扶的妈妈们。几十块钱就能解放双手，边吸奶边玩手机，真的太需要了。强烈安利给所有母乳妈妈。',
    author: '母乳喂养小助手',
    likes: 1234,
    comments: [
      { content: '这个真的好用', likes: 8 },
      { content: '哪里买', likes: 3 },
      { content: '会不会掉啊', likes: 5 },
    ],
    collects: 567,
    shares: 123,
    coverType: 'scenario',
    brandMentioned: '未提及',
    analysis: {
      score: 48,
      strategy: 'not_recommended',
      keywords: ['免手扶文胸', '母乳神器', '吸奶器配件'],
      targetAudience: ['母乳妈妈', '吸奶器用户'],
      strengths: ['场景明确，价格敏感型用户友好'],
      weaknesses: [
        '未提及BOLOLO或任何品牌，投流后用户无法直接转化为品牌流量',
        '内容过于简单，信息量低',
        '互动量一般',
      ],
      recommendation:
        '不建议优先投流。如果BOLOLO有免手扶相关配件，可考虑用类似的"价格锚点"策略做品牌内容，而非投这篇无品牌的内容。',
      suggestedBudget: 0,
      expectedCPA: 0,
      commentIntentRate: 0.2,
      contentQuality: '通用配件推荐，无品牌关联，投流性价比低',
      matchScore: { newUser: 30, oldUser: 20 },
    },
    analyzedAt: '2026-07-03T10:45:00Z',
  },
  {
    id: '17',
    title: 'BOLOLO波咯咯—以智慧创新赋能科学育儿',
    content:
      'BOLOLO波咯咯秉持"为新生家庭提供优异的产品和服务"的使命，深耕智能喂养领域10+年，聚焦智能喂养的全场景解决方案，发展成为母婴电器头部品牌。多年蝉联领先天猫、京东母婴电器销量，2019年入选福布斯AIoT百强。',
    author: 'BOLOLO官方号',
    likes: 234,
    comments: [
      { content: '支持国货', likes: 5 },
      { content: '波咯咯的产品确实好用', likes: 8 },
    ],
    collects: 67,
    shares: 23,
    coverType: 'review',
    brandMentioned: 'BOLOLO',
    analysis: {
      score: 30,
      strategy: 'not_recommended',
      keywords: ['BOLOLO', '波咯咯', '母婴电器品牌', '智能喂养'],
      targetAudience: ['品牌搜索用户'],
      strengths: ['官方品牌信息，适合做品牌专区承接'],
      weaknesses: [
        '纯品牌介绍内容，缺乏用户视角和种草力',
        '互动极低，硬广感强，不适合信息流投放',
        '小红书用户反感硬广，投流CTR预估极低',
      ],
      recommendation:
        '不建议信息流投流。此类内容适合用作品牌搜索广告的素材（当用户主动搜"波咯咯"时展示），或作为主页置顶内容。预算应分配给KOC种草笔记而非官方硬广。',
      suggestedBudget: 0,
      expectedCPA: 0,
      commentIntentRate: 0.05,
      contentQuality: '官方硬广，不符合小红书内容生态，投流效果差',
      matchScore: { newUser: 5, oldUser: 40 },
    },
    analyzedAt: '2026-07-03T10:46:00Z',
  },
  {
    id: '18',
    title: '🌛深夜泡奶，这玩意智商税？',
    content:
      '宝宝半夜的第一口奶总让我这个当妈的忙得焦头烂额！有时候奶摇好了宝宝又想睡觉，过了一会奶又凉了。不过在最近朋友给我推荐了一款自动摇奶器，温差精准到离谱，一小时后温差＜1℃。还自带小夜灯，深夜静音分贝仪实测＜60db，双向摇奶0气泡0结块。一键解冻模式15分钟就能化冻+暖奶。拥有这款乐亲摇奶器，宝宝喝奶再也不用等啦。',
    author: '夜奶战士',
    likes: 3456,
    comments: [
      { content: '摇奶器真的是智商税吗？看了想买了', likes: 34 },
      { content: '乐亲和小白熊的摇奶器哪个好？', likes: 23 },
      { content: '波咯咯的摇奶功能怎么样？', likes: 8 },
      { content: '深夜泡奶真的崩溃，种草了', likes: 45 },
    ],
    collects: 1987,
    shares: 456,
    coverType: 'story',
    brandMentioned: '乐亲',
    analysis: {
      score: 62,
      strategy: 'acquisition',
      keywords: ['摇奶器推荐', '摇奶器智商税', '深夜泡奶神器', '自动摇奶器测评'],
      targetAudience: ['夜间频繁泡奶的新手妈妈', '纠结是否买摇奶器的用户', '追求精准温控的品质用户'],
      strengths: [
        '"智商税"标题天然吸引点击，CTR预计高',
        '温差精准、静音等数据化卖点有说服力',
        '评论区有人主动提BOLOLO，存在截流机会',
      ],
      weaknesses: ['推广的是乐亲而非BOLOLO', 'BOLOLO摇奶功能在评论区仅被偶尔提及'],
      recommendation:
        '可小预算截流投放。定向搜索"摇奶器推荐""摇奶器有必要吗"的用户。落地页引导至BOLOLO三合一的摇奶功能对比。日预算150元。评论区安排KOC回复"波咯咯三合一自带摇奶，不用单独买"。',
      suggestedBudget: 150,
      expectedCPA: 38,
      commentIntentRate: 0.45,
      contentQuality: '场景痛点明确，数据化卖点强，但品牌错位需截流策略',
      matchScore: { newUser: 65, oldUser: 40 },
    },
    analyzedAt: '2026-07-03T10:47:00Z',
  },
  {
    id: '19',
    title: '喂养台极限二选一｜差价600差在哪',
    content:
      '作为混合喂养妈妈，家里空间小，选喂养台真的挑了又挑！对比了两款热门款。小白熊三合一：1599，一体设计太适合小户型，13L大空间，一体全玻璃恒温壶。云贝X56+X55：943.5，组合款胜在性价比高，基础功能都够用。两款都很靠谱，追求省心省空间的选小白熊，追求性价比的选云贝组合款。',
    author: '安安妈妈',
    likes: 5123,
    comments: [
      { content: '1599和943差好多，真的值600的差价吗', likes: 89 },
      { content: '波咯咯三合一多少钱？怎么不对比波咯咯', likes: 67 },
      { content: '我在用波咯咯，感觉介于两者之间', likes: 34 },
      { content: '求波咯咯的对比！', likes: 23 },
    ],
    collects: 3456,
    shares: 987,
    coverType: 'comparison',
    brandMentioned: '小白熊',
    analysis: {
      score: 76,
      strategy: 'acquisition',
      keywords: ['喂养台对比', '小白熊vs云贝', '喂养台性价比', '三合一喂养台推荐'],
      targetAudience: ['预算敏感的新手宝妈', '在三款喂养台之间纠结的用户', '小户型家庭'],
      strengths: [
        '价格对比切入精准，直接覆盖比价决策用户',
        '评论区大量用户主动求BOLOLO对比，截流信号极强',
        '差价600元的讨论刺激评论互动，CES加权高',
      ],
      weaknesses: ['正文未提及BOLOLO', '需要BOLOLO产出"三款喂养台横评"内容做截流承接'],
      recommendation:
        '重点截流笔记。搜索广告定向"喂养台对比""小白熊喂养台""喂养台推荐"等词。同时建议BOLOLO尽快产出一篇"三款热门喂养台横评"的KOC笔记——因为评论区已经有大量用户主动要求看BOLOLO的对比。日预算350元。',
      suggestedBudget: 350,
      expectedCPA: 28,
      commentIntentRate: 0.55,
      contentQuality: '对比类爆文，评论区BOLOLO截流需求强烈，是竞品内容中最有价值的截流目标',
      matchScore: { newUser: 78, oldUser: 45 },
    },
    analyzedAt: '2026-07-03T10:48:00Z',
  },
  {
    id: '20',
    title: '博主招募｜即热自吸管线机体验官0元招募',
    content:
      '如果你：是家装/家居博主审美在线，刚好家里缺一个管线机，拍照构图有一手。那我们这个小澎A7管线机想请你来玩。颜值党狂喜，5档温度控制，水量随心调配，懒人友好3秒速热。用你的专业审美换一整天的喝水欢乐。参与方式见评论区。',
    author: '小澎SUREPEN',
    likes: 876,
    comments: [
      { content: '报名报名！', likes: 12 },
      { content: '我家餐边柜刚好空着', likes: 8 },
    ],
    collects: 234,
    shares: 56,
    coverType: 'review',
    brandMentioned: '小澎',
    analysis: {
      score: 20,
      strategy: 'not_recommended',
      keywords: ['管线机', '即热饮水机', '家居好物'],
      targetAudience: ['家装博主', '家居爱好者'],
      strengths: [],
      weaknesses: [
        '博主招募帖而非种草帖，目标受众非消费者',
        '品类（管线机）与母婴喂养台无关',
        '对BOLOLO无任何参考价值',
      ],
      recommendation: '不相关品类，不建议任何投流。',
      suggestedBudget: 0,
      expectedCPA: 0,
      commentIntentRate: 0,
      contentQuality: '不相关品类内容，无投流价值',
      matchScore: { newUser: 0, oldUser: 0 },
    },
    analyzedAt: '2026-07-03T10:49:00Z',
  },
]

// Stats derived from preAnalyzedNotes
export const preAnalyzedStats = {
  totalNotes: preAnalyzedNotes.length,
  recommendedCount: preAnalyzedNotes.filter((n) => n.analysis.strategy !== 'not_recommended').length,
  avgScore: Math.round(
    preAnalyzedNotes.reduce((sum, n) => sum + n.analysis.score, 0) / preAnalyzedNotes.length
  ),
  acquisitionCount: preAnalyzedNotes.filter((n) => n.analysis.strategy === 'acquisition').length,
  retentionCount: preAnalyzedNotes.filter((n) => n.analysis.strategy === 'retention').length,
  bothCount: preAnalyzedNotes.filter((n) => n.analysis.strategy === 'both').length,
  notRecommendedCount: preAnalyzedNotes.filter((n) => n.analysis.strategy === 'not_recommended').length,
  totalBudgetRecommended: preAnalyzedNotes.reduce((sum, n) => sum + n.analysis.suggestedBudget, 0),
}
